const projects = [
  {
    id: '0',
    imgSrc: './images/work1.png',
    title: 'UIDeli.com',
    services: 'Design + Development',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
  {
    id: '1',
    imgSrc: './images/work2.png',
    title: 'Koto Studio',
    services: 'Development',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
  {
    id: '2',
    imgSrc: './images/work3.png',
    title: 'Switch Black',
    services: 'Design',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
  {
    id: '3',
    imgSrc: './images/work4.png',
    title: 'ReMarket',
    services: 'Development',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
  {
    id: '4',
    imgSrc: './images/work5.png',
    title: 'Another One',
    services: 'Development',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
  {
    id: '5',
    imgSrc: './images/work6.png',
    title: 'Blender Renders',
    services: 'Design + Development',
    year: '2023',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et.',
  },
]
